version: "3.8"

services:
  api:
    ports:
      - "5432:5432"
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "lalkA49F"
      POSTGRES_DB: "cashier-api"

volumes:
  cashier-api: