package com.grappim.utils

object ErrorStatusCodes {
  const val USER_DOES_NOT_EXIST = "CASHIER.API.6900"

  const val MERCHANT_ID_IS_EMPTY = "CASHIER.API.6901"
  const val STOCK_ID_IS_EMPTY = "CASHIER.API.6902"

  const val PRODUCT_DOES_NOT_EXIST = "CASHIER.API.6903"
  const val PRODUCT_CATEGORY_DOES_NOT_EXIST = "CASHIER.API.6904"

  const val WAYBILL_DOES_NOT_EXIST = "CASHIER.API.6905"

  const val DUPLICATE_PRODUCT_NAME = "CASHIER.API.6906"
  const val DUPLICATE_PRODUCT_BARCODE = "CASHIER.API.6907"
}